# Generated by Django 2.1 on 2018-09-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20180822_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_balance',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Order'),
        ),
    ]
