# Generated by Django 2.0.6 on 2018-08-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Cj', 'Caja'), ('Pz', 'Pieza')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
