# Generated by Django 2.0.6 on 2018-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
