# Generated by Django 2.1 on 2018-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180814_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, default='images/default-01.png', null=True, upload_to='images/productos', verbose_name='Imagen Producto'),
        ),
    ]
