# Generated by Django 2.1 on 2018-09-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='standard_price',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Precio Estandar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
