# Generated by Django 2.0.6 on 2018-07-16 21:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cedis', '0001_initial'),
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('tel_1', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_2', models.CharField(blank=True, max_length=50, null=True)),
                ('cel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('cedis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedis.Cedis')),
                ('price_lists', models.ManyToManyField(to='price_list.PriceList')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Employee'),
        ),
        migrations.AddField(
            model_name='client',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_list.PriceList'),
        ),
        migrations.AddField(
            model_name='client',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedis.Route'),
        ),
    ]
