# Generated by Django 2.0.6 on 2018-07-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='price_lists',
            field=models.ManyToManyField(blank=True, null=True, to='price_list.PriceList'),
        ),
    ]
