# Generated by Django 2.0.6 on 2018-08-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180716_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_condition',
            field=models.CharField(blank=True, choices=[('CTDO', 'Contado'), ('CRED', 'Credito')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='call_visit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
