# Generated by Django 2.0.6 on 2018-08-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20180820_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='call_visit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Llamada/Visita'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Razón Social'),
        ),
    ]
