# Generated by Django 2.0.6 on 2018-07-16 21:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cedis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixedProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=30, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('cedis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedis.Cedis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=30, verbose_name='Precio')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_list.PriceList')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedis.CedisProduct')),
            ],
        ),
        migrations.AddField(
            model_name='mixedproductlist',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_list.PriceList'),
        ),
        migrations.AddField(
            model_name='mixedproductlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedis.MixedProduct'),
        ),
    ]
